name: "Test Add on"
description: "Test add on with local http server"
version: "1.0.0"
slug: "test_add_on"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services 
ports:
  8002/tcp: 8002
